# This is a WIP

name: CI
 
on:
  push:
    branches:
      - salah
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  prepare:    
    runs-on: self-hosted

    steps:
      - name: Get kubectl
        run: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
            echo "$(<kubectl.sha256) kubectl" | sha256sum --check
            echo Kubectl installed

      - name: Running cluster connectivity test
        run: |
            echo ${{secrets.KUBECONFIG}} | base64 -d > kubeconfig
            ./kubectl get node --kubeconfig=kubeconfig

  build:
    runs-on: self-hosted
    needs: prepare

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  test:

    runs-on: self-hosted
    needs: build

    steps:
      - name: Testing
        run: echo We are testing here
  clean:
    runs-on: self-hosted
    needs: test

    steps:
      - name: Cleaning
        run: echo We are cleaning here


