# This is a WIP

name: CI
 
on:
  push:
    branches:
      - salah
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  prepare:    
    runs-on: self-hosted

    steps:
      - name: Get kubectl
        run: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
            echo "$(<kubectl.sha256) kubectl" | sha256sum --check
            chmod +x kubectl
            echo Kubectl installed

      - name: Running cluster connectivity test
        env:
          KUBECONFIG: ${{secrets.KUBECONFIG}}
        run: |
            echo $KUBECONFIG | base64 -d > kubeconfig
            ./kubectl get node --kubeconfig=kubeconfig

  build:
    runs-on: self-hosted
    needs: prepare

    steps:
      - uses: actions/checkout@v2

      - name: Apply yaml manifests
        env:
          REPO_NAME: ${{ github.repository }}

        run: |
          echo Applying yaml manifests
          echo $REPO_NAME
          REPO_DIR=${REPO_NAME#*"nutanixservices/"*}
          echo $REPO_DIR/$REPO_DIR/manifets/
          ./kubectl apply $(ls rbac*.yaml | awk ' { print " -f $REPO_DIR/$REPO_DIR/manifets/"$1 } ') --kubeconfig=kubeconfig

  clean:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Cleaning
        run: |
          echo Removing yaml manifests
          ./kubectl delete $(ls rbac*.yaml | awk ' { print " -f $REPO_DIR/$REPO_DIR/manifets/"$1 } ') --kubeconfig=kubeconfig


